version: '3.7'
services:
  postgresql:
    image: postgres:11.3
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=Pa$$w0rd
      - POSTGRES_DB=mydatabase
    networks:
      - local
    deploy:
      update_config:
        delay: 15s
        monitor: 5s
        order: start-first
    volumes:
      - postgresql-data:/var/lib/postgresql

volumes:
  postgresql-data:

networks:
  local:
    external: true