version: '3.7'
services:
  postgresql:
    image: postgres:11.2
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123!
      - POSTGRES_DB=exampledb
    ports:
      - 5432:5432
    deploy:
      update_config:
        delay: 15s
        monitor: 5s
        order: start-first
    volumes:
      - postgresql-data:/var/lib/postgresql

volumes:
  postgresql-data:
