version: '3.6'
#docker network create --driver=overlay --attachable olgac
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.2
    ports:
      - 5601:5601
    networks:
      - olgac
networks:
  olgac:
    external: true