version: '3.7'
services:
  mountebank:
    image: andyrbell/mountebank:2.0.0
    networks:
      - local
    ports:
      - 2525:2525
      - 20001:20001
      - 30001:30001
networks:
  local:
    external: true
