version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.7.13-management-alpine
    #image: rabbitmq:3.8.0-beta.3-management-alpine
    hostname: rabbitmq
    networks:
      - local
    environment:
      - RABBITMQ_DEFAULT_USER=sa
      - RABBITMQ_DEFAULT_PASS=Sa123456
      - RABBITMQ_ERLANG_COOKIE='bjk1903'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
networks:
  local:
    external: true
volumes:
  rabbitmq-data: