version: '3.7'
services:
  gitlab:
    image: gitlab/gitlab-ce:11.9.8-ce.0
    hostname: gitlab.olgac.com
    networks:
      - local
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.olgac.com:8880'
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
    deploy:
      update_config:
        delay: 15s
        monitor: 5s
    ports:
      - '8443:443'
      - '8880:80'
      - '8822:22'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
networks:
  local:
    external: true
volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
