version: '3.7'
services:
  consul:
    image: consul:1.4.4
    hostname: consul
    networks:
      - local
    ports:
      - 8500:8500
    volumes:
      - consul-data:/consul/data
networks:
  local:
    external: true
volumes:
  consul-data:
