version: '3.6'
#docker network create --driver=overlay --attachable olgac
#curl localhost:9200/_cat/health;curl localhost:9200/_cat/nodes?v;curl localhost:9200/_cluster/health?pretty;curl localhost:9200/_nodes/process?pretty
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    hostname: elasticsearch
    networks:
      - olgac
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
networks:
  olgac:
    external: true
volumes:
  elasticsearch-data: