version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    hostname: elasticsearch
    networks:
      - local
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
networks:
  local:
    external: true
volumes:
  elasticsearch-data:
