version: '3.7'
services:
  couchbase:
    image: couchbase:6.0.1
    networks:
      - local
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
    volumes:
      - couchbase-data:/opt/couchbase/var
networks:
  local:
    external: true
volumes:
  couchbase-data:
