version: '3.7'
services:
  mongo:
    image: mongo:4.0.7-xenial
    networks:
      - local
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data
networks:
  local:
    external: true
volumes:
  mongo-data:
