version: '3.6'
services:
  redis:
    image: redis:5.0.4-alpine
    hostname: redis
    networks:
      - olgac
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
networks:
  olgac:
    external: true
volumes:
  redis-data:
