version: '3.7'
services:
  redis:
    image: redis:5.0.4-alpine
    hostname: redis
    networks:
      - local
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
networks:
  local:
    external: true
volumes:
  redis-data:
